name: Ruby CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ruby-ci:
    name: Ruby ${{ matrix.ruby }} - ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
          - head
          - jruby
          - jruby-head
          - truffleruby
          - truffleruby-head
        include:
          - ruby: head
            continue-on-error: true
          - ruby: jruby-head
            continue-on-error: true
          - os: windows-latest
            ruby: mingw
          - os: windows-latest
            ruby: mswin
          - os: windows-latest
            ruby: jruby
            continue-on-error: true
          - os: macos-latest
            ruby: '3.1'
          - os: macos-latest
            ruby: '3.2'
          - os: ubuntu-22.04
            ruby: head
            continue-on-error: true
          - os: ubuntu-22.04
            ruby: '3.1'
          - os: ubuntu-22.04
            ruby: '3.2'
          - os: ubuntu-22.04
            ruby: '3.3'
          - os: ubuntu-22.04
            ruby: truffleruby-head
            continue-on-error: true

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.continue-on-error || false }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ruby/setup-ruby@2a18b06812b0e15bb916e1df298d3e740422c47e # v1.203.0
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: latest
          bundler: 2
          bundler-cache: true

      - run: bundle exec ruby -S rake test --trace

      - if: matrix.os == 'ubuntu-22.04' && matrix.ruby == '3.2'
        run: bundle exec standardrb
